### ISSUE TITLE
Stopped inserting from right click menu

### ISSUE THREAD

**Issue by ThomByxbe** [przybylski/permanent-clipboard#1]
I love this extensioin! BUT, about a week ago it stopped inserting (or showing anything available to insert ) from right click menu. See attached photo (screen 001). As you can also see, I can no longer add text to permanent-clipboard from right click menu. 

The entries I made before this issue started and I can xsee them from the tool bar button. See Photo (screen 002).

How can I get the right click menu.to work again without loseing the data all ready stord in the extension?

![screen 001](https://cloud.githubusercontent.com/assets/14813847/11889111/48596202-a513-11e5-84e1-ab02e8c4c15d.jpg)
![screen 002](https://cloud.githubusercontent.com/assets/14813847/11889110/4859229c-a513-11e5-8f43-064c453374cb.jpg)

**Comment by przybylski** [comment]
Hmm... I cannot reproduce this bug. Could you open chrome://extensions and reload permanent clipboard?
