### ISSUE TITLE
Podkategorie

### ISSUE THREAD

**Issue by lovelypl** [przybylski/permanent-clipboard#3]
Dałoby się zrobić podkategorie dla dodawanych elementów. 
W momencie kiedy używam np. 50 "canned responses" wygodniej by było to jakoś podzielić na logiczne podkategorie.
I czy limit dla "pamięci synchronizowanej" jest narzucony odgórnie? Bo boję się, że może mi zabraknąć miejsca :)

**Comment by przybylski** [comment]
Powoli pracuję nad kategoriami.
Limit pamięci synchronizowanej jest narzucony przez google, można go zwiększyć przez pewne sztuczki i nad tym też myślę.
