### ISSUE TITLE
amp;

### ISSUE THREAD

**Issue by funksucker** [przybylski/permanent-clipboard#4]
Hey I love my permanent clipboard but what really bugs me is I get things like "amp;" & "&nbsp" in there when I save.  So when I come to paste stuff in I have to delete all those bits which is time consuming.  Can you fix this please?

**Comment by przybylski** [comment]
Hi! Thanks for the feedback. Could you point me to the website from which you copy the text which produced the incorrect value?
Thanks!

**Comment by funksucker** [comment]
Hi.  It's ok I get it now from what you said.  If I type it in myself it
saves perfectly.


Thank you!


*Mick Lee ~ Songwriter*

*Lyrics . Melodies . Composition . Production*


*Soundcloud <https://soundcloud.com/mick-lee/sets/recent-works-c0-writes>
link*
facebook <https://www.facebook.com/mick.lee.549> twitter
<https://twitter.com/mr_mick_lee>
