### ISSUE TITLE
Can't create backup of local storage

### ISSUE THREAD

**Issue by onewhitedog** [przybylski/permanent-clipboard#7]
Hi, I am running v2.3 in local storage mode.
I would like to backup all my clippings but when I click Create in the backup section nothing happens.

I would appreciate a fix before I accidentally lose all my clips.
Thank you.

**Comment by przybylski** [comment]
Backup should trigger file download, so the backup should be in your backup folder. Could you check there?
Also what OS you are running?

**Comment by onewhitedog** [comment]
Hello Bartosz,

Thank you for responding.
I am running Windows 10 Pro.
What is the backup folder called?

When I click on CREATE to start the backup, no window pops up to prompt for a folder or filename, just nothing at all happens.

Kind regards,
Sheryn

**Comment by przybylski** [comment]
Sorry for being not too precise.
By backup folder I mean the default Download folder on you machine.
Could you also check in chrome://downloads/ if a file names permanentClipboard.backup is being saved? Thanks!

**Comment by onewhitedog** [comment]
Hello Bartosz,

There is no backup file in my Downloads folder.
There is no backup file in chrome://downloads either.
I also did a search for a file named permanentClipboard.backup on all my drives (C,D) and nothing was found.

Kind regards,
Sheryn

**Comment by przybylski** [comment]
Are you getting any error message in popup? Could you check in developer console (right click -> inspect) for errors.
I checked for errors in events tracking and I haven't found any errors while creating backup.
Did you alter the source in any way?

**Comment by onewhitedog** [comment]
Hi Bartosz,

There is no pop-up.
When I click Create, there is no pop-up.
I have not altered the source, I wouldn’t know how to.

I’ve worked out how to inspect for errors, and I attach this screenshot.
[cid:image002.png@01D419F0.70D9E2C0]

I hope this helps.
I get the feeling the answer is going to be to uninstall and reinstall which is going to make me lose all my clippings anyway.

Regards, Sheryn

**Comment by przybylski** [comment]
Sheryn,

Could you please sent me the screenshot directly to my email? GitHub is not supporting inserting images from email responses.
I will be able to help you better in direct contact.
Thanks!
