### ISSUE TITLE
No Longer Copies to Windows 10 Clipboard As Of Today

### ISSUE THREAD

**Issue by pwhuff** [przybylski/permanent-clipboard#8]
When selecting an item from the Chrome plugin nothing happens. I have to manually edit any of my entries and select CTL + C in order to get any clipboards. Out of curiosity I installed it fresh to a new Chrome profile and it still does not copy any data to the clipboard. I have plenty of sync space left in that I only use a handful of entries.

**Comment by przybylski** [comment]
Hi, I missed a file while I was releasing new version, I am now rolling fixed version, sorry for inconvenience
